// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZW_tlu0r62-hufTOADXNHu3kDAJI2-rI',
    appId: '1:80891904258:web:97383cba8b21c30569421b',
    messagingSenderId: '80891904258',
    projectId: 'short-video-player-7ec8f',
    authDomain: 'short-video-player-7ec8f.firebaseapp.com',
    storageBucket: 'short-video-player-7ec8f.appspot.com',
    measurementId: 'G-9D439GFJJP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgbxLGgHcN61T0j1ZWH4Q9CmNUi6Dl-yg',
    appId: '1:80891904258:android:20af8ee7cc40abaf69421b',
    messagingSenderId: '80891904258',
    projectId: 'short-video-player-7ec8f',
    storageBucket: 'short-video-player-7ec8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuSLjXFfU-XlwexUlnd6QQ2yTOfyOZgyY',
    appId: '1:80891904258:ios:2a952091fb6c0da769421b',
    messagingSenderId: '80891904258',
    projectId: 'short-video-player-7ec8f',
    storageBucket: 'short-video-player-7ec8f.appspot.com',
    iosBundleId: 'com.heysitam.videostreamingdemo.shortVideoStreamingDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuSLjXFfU-XlwexUlnd6QQ2yTOfyOZgyY',
    appId: '1:80891904258:ios:2a952091fb6c0da769421b',
    messagingSenderId: '80891904258',
    projectId: 'short-video-player-7ec8f',
    storageBucket: 'short-video-player-7ec8f.appspot.com',
    iosBundleId: 'com.heysitam.videostreamingdemo.shortVideoStreamingDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZW_tlu0r62-hufTOADXNHu3kDAJI2-rI',
    appId: '1:80891904258:web:2c9765cd03e2c70969421b',
    messagingSenderId: '80891904258',
    projectId: 'short-video-player-7ec8f',
    authDomain: 'short-video-player-7ec8f.firebaseapp.com',
    storageBucket: 'short-video-player-7ec8f.appspot.com',
    measurementId: 'G-R56HVZW2ES',
  );
}
